apiVersion: V1
kind: ReplicationController

metadata:
   name: firstrc
   labels:
        appname: votingApp
        
 spec:
    replicas: 5
    templates:
         metadata: 
                name: firstpod
                labels:
                     type: app
         spec:
                containers:
                     - name: containerRC
                       image: httpd
