apiVersion: v1
kind: Pod

metadata:
   name: podwithlimit
   labels:
      app: harrysapp
      type: frontend
      
spec: 
   containers:
      - name: harrysapp-container
        image: httpd:latest
        resource:
           requests:
               memory: 200mi
               cpu: 100m
               
               
# Please follow identation as this is yaml , i may missed somewhere some spaces which might cause failure if you just copy paste code.
