apiVersion: V1
kind: Service

metadata: 
     name: svcnodeport1
     label:
          env: PROD
          
spec:
    containers:
           type: NodePort
           ports:
               - nodePort: 32000
                 ports: 9800
                 targetPort: 80
           
           selector: 
                 type: app


# Please follow identation as this is yaml , i may missed somewhere some spaces which might cause failure if you just copy paste code.
